### ISSUE TITLE
[ORM] Tweaks needed to Article object

### ISSUE THREAD

**Issue by KOOKIIEStudios** [Bratah123/CSUFTheOnion#15]
The Article object requires a number of tweaks moving forward:
1. `summary` field
    - This should be generated on object creation; perhaps a limit of 20 words, and with trailing ellipses
2. `id` field (should to automagically generated by DB engine)

**Comment by Bratah123** [comment]
Done in: e1c4e4e06ace749edbefd379dcd12a7a6f12fad8
