### ISSUE TITLE
[DB Convenience Methods] Search for keyword

### ISSUE THREAD

**Issue by KOOKIIEStudios** [Bratah123/CSUFTheOnion#17]
To be consumed by search bar for doing keyword search of title (and/or contents).
For the purposes of this project, a naive search like sqlite's `instr` (or the more traditional `like` or `contains`)

**Comment by Bratah123** [comment]
Done in: https://github.com/Bratah123/CSUFTheOnion/commit/7f7ed93da6146819cbc5fefaa48dfcd20784ea1b
