### ISSUE TITLE
[DOCS] Add remote signing information to README

### ISSUE THREAD

**Issue by KOOKIIEStudios** [Bratah123/CSUFTheOnion#6]
## Abstract
Following feedback about not being able to run the virtualenv activation script, it should probably be better that instructions be included in the README. Write a detailed guide on setting PowerShell's execution policy to remote signed (which is what virtualenv requires), and what this means for the security for your machine.

### Additional Information
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4

**Comment by Ragnaorok** [comment]
Added detailed guide on setting PowerShell's execution policy
Completed Linux's version of installation and the execution policy

**Comment by KOOKIIEStudios** [comment]
Linux instructions do not work

a few key pointers:
1. Most distributions use `python3` instead of just `python`
2. `venv` folder structure is different on Linux
